### ISSUE TITLE
Fresh start: TypeError

### ISSUE THREAD

**Issue by sigmasoldi3r** [crisward/preact-coffee#1]
Browser screen appears blank and the console says: `TypeError: setting getter-only property "children"`

## Steps to reproduce:

1. Clone repo
2. `npm install`
3. `npm run build`
4. `npm run watch`
5. Open _index.html_

## Versions

Node: v10.7.0
Npm: 6.2.0
Coffee/Preact: Built-in

**Comment by crisward** [comment]
Updated all deps and tried it with node 10.9.0 - seems to be working fine again. I also had to remove the linkstate mixin as preact/react no longer use those.

**Comment by sigmasoldi3r** [comment]
Thanks for your time! Now is working, but I had to replace the package dependency of `coffee-script` with `coffeescript`, because npm install yields this otherwise:

```
npm WARN preact-coffee@1.0.0 No repository field.

npm ERR! code ETARGET
npm ERR! notarget No matching version found for coffee-script@1.12.8
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'preact-coffee'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pablo\AppData\Roaming\npm-cache\_logs\2018-09-06T13_42_39_731Z-debug.log
```
Then, after changing the dependency and removing package-lock.json:
```
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
```
But only a warning, is working.

**Comment by crisward** [comment]
Thanks, I don't have coffee-script in my `package.json` so I've removed the lock file. Thanks for checking.
